version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: soundify-backend
    restart: always
    environment:
      SUPABASE_URL: ${SUPABASE_URL:-}
      SUPABASE_KEY: ${SUPABASE_KEY:-}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-}
      Frontend_url: ${Frontend_url:-http://localhost:5173}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/__pycache__
    networks:
      - soundify-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: soundify-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    networks:
      - soundify-network
    environment:
      VITE_API_URL: http://localhost:8000
    command: npm run dev

networks:
  soundify-network:
    driver: bridge